DROP TABLE Artist CASCADE CONSTRAINT;
DROP TABLE Title  CASCADE CONSTRAINT;
DROP TABLE Prices CASCADE CONSTRAINT;

CREATE TABLE Artist(
Artist_ID NUMBER,
First_Name VARCHAR2(15),
Last_Name VARCHAR2(15),
CONSTRAINT Artist_ArtistID_PK PRIMARY KEY(Artist_ID)
);

CREATE TABLE Title (
Title_ID NUMBER ,
Description VARCHAR2(50) CONSTRAINT Title_Desc_NN Not Null,
Artist_ID NUMBER, 
CONSTRAINT Title_TitleID_PK PRIMARY KEY(Title_ID),
CONSTRAINT Title_ArtistID_FK FOREIGN KEY(Artist_ID) 
REFERENCES Artist(Artist_ID) ON DELETE CASCADE
);

CREATE TABLE Prices (
Title_ID NUMBER,
Price_Date Date,
Amount Number 
);
ALTER TABLE Prices ADD CONSTRAINT Prices_TitleID_Date_PK
PRIMARY KEY (Title_ID , Price_Date);

ALTER TABLE Prices MODIFY Amount CONSTRAINT Prices_Amount_NN NOt Null ;

ALTER TABLE Prices ADD CONSTRAINT Prices_TitleID_FK 
FOREIGN KEY (Title_ID) REFERENCES Title(Title_ID) 
ON DELETE CASCADE;