PROMPT  Question 1: DROP TABLES

DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE AUTHOR CASCADE CONSTRAINTS;
DROP TABLE WRITEN_BY CASCADE CONSTRAINTS;
DROP TABLE PUBLISHER CASCADE CONSTRAINTS;

PROMPT  Question 2: CREATE TABLES

CREATE TABLE BOOK(
    ISBN NUMBER,
    TITLE VARCHAR2(40),
    PUBLISHER_ID NUMBER,
    PUBLISHER_DATE DATE
);

CREATE TABLE AUTHOR(
    AUTHOR_ID CHAR(8),
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20)
);

CREATE TABLE WRITEN_BY(
    ISBN NUMBER,
    AUTHOR_ID CHAR(8)
);

CREATE TABLE PUBLISHER(
    PUBLISHER_ID NUMBER,
    PUBLISHER_NAME VARCHAR2(20),
    PUBLISHER_ADDRESS VARCHAR2(20)
);

PROMPT  Question 3: Add Primary Keys

ALTER TABLE BOOK ADD CONSTRAINTS BOOK_ISBN_PK PRIMARY KEY (ISBN);
ALTER TABLE AUTHOR ADD CONSTRAINTS AUTHOR_AUTHOR_ID_PK PRIMARY KEY (AUTHOR_ID);
ALTER TABLE WRITEN_BY ADD CONSTRAINTS WRITEN_BY_ISBN_PK PRIMARY KEY (ISBN);
ALTER TABLE PUBLISHER ADD CONSTRAINTS PUBLISHER_PUBLISHER_ID_PK PRIMARY KEY (PUBLISHER_ID);

PROMPT  Question 4: Add Foreign Keys

ALTER TABLE WRITEN_BY ADD CONSTRAINTS WRITEN_BY_ISBN_FK FOREIGN KEY (ISBN) REFERENCES BOOK (ISBN) ON DELETE CASCADE;
ALTER TABLE WRITEN_BY ADD CONSTRAINTS WRITEN_BY_AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID) ON DELETE CASCADE;
ALTER TABLE BOOK ADD CONSTRAINTS BOOK_PUBLISHER_ID_FK FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (PUBLISHER_ID) ON DELETE CASCADE;

PROMPT  Question 5: ADD COLUMN

ALTER TABLE BOOK ADD (BOOK_CATEGORIES VARCHAR2(30));
ALTER TABLE BOOK ADD (PETS VARCHAR2(20));

ALTER TABLE BOOK REMANE COLUMN PETS TO PET;

PROMPT  Question 6: MODIFY COLUMN

ALTER TABLE PUBLISHER MODIFY (PUBLISHER_NAME VARCHAR2(30));

PROMPT  Question 7: CHECK CONSTRAINTS

ALTER TABLE BOOK ADD CONSTRAINTS BOOK_BOOK_CATEGORIES_CK CHECK (BOOK_CATEGORIES IN ('COMPUTERS','MATH','SCIENCE'));

