CONNECT / AS SYSDBA
-- Give all privileges to User in order to create Views, Synonyms, Sequences, ...
GRANT ALL PRIVILEGES TO demo;
CONNECT demo/demo

DROP INDEX DEPT_LOCATION_ID_IDX;
DROP INDEX EMP_DEPARTMENT_ID_IDX;
DROP SYNONYM DEPT2;

PROMPT QUESTION 1 - Creating the INDEXE

-- CREATE INDEX EMP_DEPARTMENT_ID_IDX ON EMP (DEPARTMENT_ID);
-- WE cannot create an INDEX for a column that is already indexed.

PROMPT QUESTION 2 - Creating the SYNONYM

CONNECT / AS SYSDBA
GRANT CREATE SYNONYM TO demo;
CONNECT demo/demo
CREATE SYNONYM DEPT2 FOR DEPARTMENT;

PROMPT QUESTION 3 - Creating the INDEXE

CREATE INDEX DEPT_LOCATION_ID_IDX ON DEPARTMENT (LOCATION_ID);