CONNECT / AS SYSDBA
-- Give all privileges to User in order to create Views, Synonyms, Sequences, ...
GRANT ALL PRIVILEGES TO demo;
CONNECT demo/demo

DROP SEQUENCE DEPT_ID_SEQ;
DROP INDEX EMP_DEPT_ID_IDX;
DROP VIEW SALARY_VIEW;

PROMPT QUESTION 1 - Creating SALARY_VIEW

CREATE VIEW SALARY_VIEW AS 
SELECT LAST_NAME "EMPLOYEE NAME", SALARY , COMMISSION
FROM EMPLOYEE;

PROMPT QUESTION 2.1 - Creating the SEQUENCE

CREATE SEQUENCE DEPT_ID_SEQ INCREMENT BY 10 START WITH 200 MAXVALUE 1000;

PROMPT QUESTION 2.2 - Displaying SEQUENCE DESCRIPTION 

SELECT SEQUENCE_NAME , MIN_VALUE , MAX_VALUE ,INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES ;

PROMPT QUESTION 3.1 - Inserting Data in Table DEPT

INSERT INTO DEPT VALUES (DEPT_ID_SEQ.nextval, 'Education');
INSERT INTO DEPT VALUES (DEPT_ID_SEQ.nextval, 'Administration');

PROMPT QUESTION 3.2 - Inserting Data in Table Department

INSERT INTO DEPARTMENT VALUES (50, 'Education', 122);
INSERT INTO DEPARTMENT VALUES (51, 'Administration', 122);

PROMPT QUESTION 3.3 - Verifying Additions

SELECT * FROM DEPT;
SELECT * FROM DEPARTMENT;
