PROMPT DROP SEQUENCE

DROP SEQUENCE STUDENT_ID_SEQ;
DROP SEQUENCE EXAM_ID_SEQ;

PROMPT  Question 1: DROP TABLES

DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE EXAM CASCADE CONSTRAINTS;
DROP TABLE EVALUATION CASCADE CONSTRAINTS;

PROMPT  Question 2: CREATE TABLES

CREATE TABLE STUDENT(
    STUDENT_ID NUMBER,
    LAST_NAME VARCHAR2(25),
    FIRST_NAME VARCHAR2(25)
);

CREATE TABLE EXAM(
    EXAM_ID NUMBER,
    NAME VARCHAR2(25)
);

CREATE TABLE EVALUATION(
    STUDENT_ID NUMBER,
    EXAM_ID NUMBER,
    GRADE NUMBER
);

PROMPT  Question 3: Add Primary Keys

ALTER TABLE STUDENT ADD CONSTRAINTS STUDENT_STUDENT_ID_PK PRIMARY KEY (STUDENT_ID);
ALTER TABLE EXAM ADD CONSTRAINTS EXAM_EXAM_ID_PK PRIMARY KEY (EXAM_ID);
ALTER TABLE EVALUATION ADD CONSTRAINTS EVALUATION_STUID_EXAMID_PK PRIMARY KEY (STUDENT_ID,EXAM_ID);

PROMPT  Question 4: Add Foreign Keys

ALTER TABLE EVALUATION ADD CONSTRAINTS EVALUATION_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID) ON DELETE CASCADE;
ALTER TABLE EVALUATION ADD CONSTRAINTS EVALUATION_EXAM_ID_FK FOREIGN KEY (EXAM_ID) REFERENCES EXAM (EXAM_ID) ON DELETE CASCADE;

PROMPT  Question 5: CHECK CONSTRAINTS

ALTER TABLE EXAM ADD CONSTRAINTS EXAM_NAME_CK CHECK (NAME IN ('MIDTERM','FINAL EXAM','PROJECT'));
ALTER TABLE EVALUATION ADD CONSTRAINTS EVALUATION_GRADE_CK CHECK (GRADE >= 0 AND GRADE <= 100);

PROMPT  Question 6: ADD COLUMN

ALTER TABLE STUDENT ADD (STATUS VARCHAR2(15));

PROMPT  Question 7: CREATE SEQUENCE

CREATE SEQUENCE STUDENT_ID_SEQ INCREMENT BY 10 START WITH 1011;
CREATE SEQUENCE EXAM_ID_SEQ INCREMENT BY 1 START WITH 1;

PROMPT INSERT DATA IN STUDENT

INSERT INTO STUDENT(STUDENT_ID,FIRST_NAME,LAST_NAME) VALUES (STUDENT_ID_SEQ.NEXTVAL, 'TONY', 'SMITH');
INSERT INTO STUDENT(STUDENT_ID,FIRST_NAME,LAST_NAME) VALUES (STUDENT_ID_SEQ.NEXTVAL, 'HELEN', 'ROY');

PROMPT INSERT DATA IN EXAM

INSERT INTO EXAM(EXAM_ID, NAME) VALUES (EXAM_ID_SEQ.NEXTVAL, 'MIDTERM');
INSERT INTO EXAM(EXAM_ID, NAME) VALUES (EXAM_ID_SEQ.NEXTVAL, 'PROJECT');
INSERT INTO EXAM(EXAM_ID, NAME) VALUES (EXAM_ID_SEQ.NEXTVAL, 'FINAL EXAM');

PROMPT INSERT DATA IN EVALUATION

INSERT INTO EVALUATION(STUDENT_ID,EXAM_ID,GRADE) VALUES (1011, 1, 75);
INSERT INTO EVALUATION(STUDENT_ID,EXAM_ID,GRADE) VALUES (1021, 1, 90);
INSERT INTO EVALUATION(STUDENT_ID,EXAM_ID,GRADE) VALUES (1011, 2, 87);
INSERT INTO EVALUATION(STUDENT_ID,EXAM_ID,GRADE) VALUES (1021, 2, 85);

SELECT * FROM STUDENT;
SELECT * FROM EXAM;
SELECT * FROM EVALUATION;