-- DISPLAY THE NUMBER OF CUSTOMERS FOR EACH COUNTRY.
SELECT COUNT(*) 
AS NO_OF_CUSTOMERS, COUNTRY 
FROM CUSTOMER
GROUP BY COUNTRY;

-- DISPLAY THE EMPLOYEE_ID AND THE NUMBER OF ORDERS FOR EACH EMPLOYEE HAVING MORE THAN. 
SELECT EMPLOYEE_ID,COUNT(ORDER_ID) 
AS NB_OF_ORDERS 
FROM ORDERS
HAVING COUNT(ORDER_ID) > 10
GROUP BY EMPLOYEE_ID;

-- DISPLAY THE TOTAL OF EACH ORDER WHERE ORDER_ID IS GREATER THAN 11072.
SELECT ORDER_ID, SUM((QUANTITY*UNIT_PRICE)-(QUANTITY*UNIT_PRICE*DISCOUNT))
AS TOTAL_PRICE 
FROM ORDERDETAILS
WHERE ORDER_ID > 11072
GROUP BY ORDER_ID;

-- DISPLAY THE COMPANY_NAME OF CUSTOMERS WHO DID NOT SUBMIT ANY ORDERS.
SELECT DISTINCT COMPANY_NAME 
FROM CUSTOMER
WHERE CUSTOMER_ID 
NOT IN (SELECT CUSTOMER_ID FROM ORDERS) 
ORDER BY 1;

-- DISPLAY THE COMPANY_NAME OF CANADIAN CUSTOMERS WHO ARE LOCATED IN CITIES WHERE THERE IS AT LEAST ONE SUPPLIER.
SELECT COMPANY_NAME,CITY 
FROM CUSTOMER
WHERE CITY IN (SELECT DISTINCT CITY 
FROM SUPPLIER 
WHERE UPPER(COUNTRY) = 'CANADA');

-- DISPLAY THE FIRST_NAME , LAST_NAME AND TITLE OF ALL EMPLOYEES WHO HAVE A SALARY GREATER THAN ALL EMPLOYEES WHO HAVE THE TITLE OF 'SALES REPRESENTATIVE'.
SELECT FIRST_NAME, LAST_NAME, TITLE 
FROM EMPLOYEE
WHERE SALARY > ALL (SELECT SALARY
FROM EMPLOYEE
WHERE UPPER(TITLE) = 'SALES REPRESENTATIVE');

-- DISPLAY THE LIST OF SUPPLIERS WHO ARE SELLING PRODUCTS HAVING A PRICE IS GREATER THAN 50. 
SELECT S.SUPPLIER_ID AS SUPPLIER_ID, S.COMPANY_NAME AS COMPANY_NAME, P.UNIT_PRICE AS UNIT_PRICE
FROM  SUPPLIER S JOIN PRODUCT P
ON (S.SUPPLIER_ID = P.SUPPLIER_ID)
WHERE UNIT_PRICE > 50;


-- DISPLAY THE LIST OF PRODUCT_NAME OF PRODUCTS HAVING THE SAME UNIT_PRICE.
SELECT P.PRODUCT_NAME, Q.UNIT_PRICE,Q.PRODUCT_NAME
FROM PRODUCT P JOIN PRODUCT Q
ON P.UNIT_PRICE = Q.UNIT_PRICE
WHERE P.PRODUCT_ID != Q.PRODUCT_ID
ORDER BY Q.UNIT_PRICE DESC;


-- DISPLAY THE FIRST_NAME, LAST_NAME AND THE NUMBER OF ORDERS FOR EACH EMPLOYEE HAVING MORE THAN 10 ORDER.
SELECT E.FIRST_NAME AS FIRST_NAME, E.LAST_NAME AS LAST_NAME, COUNT(ORDER_ID) AS NB_OF_ORDERS
FROM EMPLOYEE E 
JOIN ORDERS O
ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
GROUP BY FIRST_NAME,LAST_NAME
HAVING COUNT(O.ORDER_ID) > 10;
 
-- DISPLAY THE NAMES OF SUPPLIERS WHO SELL PRODUCTS THAT HAVE THE SAME UNIT PRICE AS THE PRODUCT STEELEYE STOUT.
 SELECT S.COMPANY_NAME,P.UNIT_PRICE
 FROM SUPPLIER S JOIN PRODUCT P 
 ON S.SUPPLIER_ID=P.SUPPLIER_ID 
 WHERE P.UNIT_PRICE =(SELECT UNIT_PRICE FROM PRODUCT 
 WHERE UPPER(PRODUCT_NAME)='STEELEYE STOUT');
 
 COMMIT; 